<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */

/**
 * Implements hook_theme().
 */
function dummy_theme($existing, $type, $theme, $path): array {
  return [
    'dummy_example_first' => [
      'variables' => [],
    ],
    // Данный пример будет использоваться для вывода содержимого в виде списка,
    // а его препрцоесс мы венесем в отдельный файл.
    'dummy_example_second' => [
      'variables' => [
        'list_type' => 'ul',
        'items' => NULL,
        'attributes' => NULL,
      ],
      'file' => 'dummy.theme.inc',
    ],
    'dummy_example_quote' => [
      'variables' => [
        'quote' => NULL,
        'author' => NULL,
        'year' => NULL,
        'source_title' => NULL,
        'source_url' => NULL,
      ],
      'file' => 'dummy.theme.inc',
      'pattern' => 'dummy_example_quote__',
    ],
    'hook_theme_form_example' => [
      'render element' => 'form',
      'file' => 'dummy.theme.inc',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 * Обработчик переменных для первого примера.
 */
function template_preprocess_dummy_example_first(&$variables) {
  $date_formatter = \Drupal::service('date.formatter');
  $variables['date'] = $date_formatter->format(time());
}
