collect_phone.form:
  path: '/collect-phone'
  defaults:
    _title: 'Collect Phone - Form API example.'
    # Подгружаем форму по неймспейсу.
    _form: '\Drupal\custom_configuration\Form\CollectPhone'
  requirements:
    _permission: 'access content'

custom_configuration.collect_phone_admin_settings:
  path: '/admin/config/custom-configuration/phone-settings'
  defaults:
    _form: '\Drupal\custom_configuration\Form\CollectPhoneSettings'
    _title: 'Settings for CollectPhone form.'
  requirements:
    _permission: 'administer site configuration'

custom_configuration.admin_config_custom_configuration:
  path: '/admin/config/custom_configuration'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Custom Configuration'
  requirements:
    _permission: 'access administration pages'
