custom_configuration.admin_config_custom_configuration:
  title: 'Custom_configuration'
  parent: system.admin_config
  route_name: custom_configuration.admin_config_custom_configuration
  weight: -50

custom_configuration.collect_phone_settings:
  title: 'Collect Phone settings'
  description: 'In this settings you can set default phone number for collect phone form.'
  parent: custom_configuration.admin_config_custom_configuration
  route_name: custom_configuration.collect_phone_admin_settings
  weight: 1
